name: Despertador Streamlit

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Visitar la app
        run: |
          curl --location --request GET 'https://flowpark-valet.streamlit.app/'
